name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_NUGET_REPOSITORY: 'https://github.com/lerppana/vcpkg-registry.git'
  VCPKG_KEEP_ENV_VARS: GITHUB_AUTHORIZATION_TOKEN;BLENDER_ROOT

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows-prod
            VULKAN_SDK: VulkanSDK
            vulkan_branch: windows
            generator: Ninja
            mono: ''
    env:
      VCPKG_FEATURE_FLAGS: manifests,versions,registries
      VCPKG_MANIFEST_NO_DEFAULT_FEATURES: OFF
      buildDir: ${{ github.workspace }}/b/vcpkg_submod_manifest
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
      - uses: lerppana/game_build_pipeline@main
        with:
          PAT: ${{ secrets.PAT }}
